"""empty message

Revision ID: 549992973f71
Revises: 233024fd6762
Create Date: 2024-07-28 15:00:06.929678

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '549992973f71'
down_revision: Union[str, None] = '233024fd6762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
