"""empty message

Revision ID: 8725f4e5a9a9
Revises: 9c980bf53e5f
Create Date: 2024-07-10 15:37:51.801170

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8725f4e5a9a9'
down_revision: Union[str, None] = '9c980bf53e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
