"""empty message

Revision ID: b2f8236eb0da
Revises: 2f0498cd9185
Create Date: 2024-07-06 17:59:05.759043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f8236eb0da'
down_revision: Union[str, None] = '2f0498cd9185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_user_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('notification_user_id_fkey', 'notification', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
