"""empty message

Revision ID: cd4df6892f34
Revises: edc02d5e1720
Create Date: 2024-07-28 09:47:42.615601

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cd4df6892f34'
down_revision: Union[str, None] = 'edc02d5e1720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_link_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_telegram_link_key', 'users', ['telegram_link'])
    # ### end Alembic commands ###
