"""empty message

Revision ID: e5aa64511d9a
Revises: 78b6167604e0
Create Date: 2024-07-21 16:07:19.279880

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e5aa64511d9a'
down_revision: Union[str, None] = '78b6167604e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
