"""empty message

Revision ID: fb6df310c49a
Revises: d8ae3162bf28
Create Date: 2024-07-21 14:46:22.590486

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fb6df310c49a'
down_revision: Union[str, None] = 'd8ae3162bf28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
